# ./github/dependabot.yml
##
# Dependabot configuration for Bedrock
#
# Check for updates to Composer packages weekly
##

version: 2
updates:
  - package-ecosystem: "composer" # See documentation for possible values
    directory: "/site" # Location of package manifests
    target-branch: "staging"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
