# .github/workflows/dryrun-staging.yml
##
# Dry-run deploy to a temporary directory in the staging environment with Trellis
##

name: ðŸ§ª Dry-run to staging
run-name: dry-run-staging

on:
  workflow_dispatch:
  pull_request:
    branches: [staging]

env:
  environment: staging
  script: |
    ---
    - name: "This is a dry-run, delete the deploy."
      ansible.builtin.file:
        state: absent
        path: "{{ deploy_helper.new_release_path }}"

    - name: "This is a dry-run, stop here."
      meta: end_play
  extra-vars: |
    {
      "deploy_build_after": [
        "{{ playbook_dir }}/roles/deploy/hooks/build-after.yml",
        "{{ playbook_dir }}/deploy-hooks/build-after.yml",
        "/build-after.yml"
      ],
      "dry_run": true,
      "project_root": "/tmp/trellis"
    }

jobs:
  dryrun-staging:
    runs-on: ubuntu-latest
    steps:

      # Checkout the repo
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      # Create a file with the contents of the script environment variable
      - name: Create script file
        run: echo "${{ env.script }}" > build-after.yml

      # Create a yml file with the contents of the extra-vars
      - name: Create extra-vars file
        run: |
          echo "${{ env.extra-vars }}" > extra-vars.json

      # Deploy site to staging
      - uses: ./.github/actions/trellis-cli
        name: Dry-run deploy to staging
        if: github.event.pull_request.merged || github.event_name == 'workflow_dispatch' || github.repository != 'MWDelaney/trellis-template'
        with:
          extra-vars: '"@file:/extra-vars.json"'
          environment: ${{ env.environment }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          trellis_site_slug: ${{ secrets.TRELLIS_SITE_SLUG }}
          trellis_deploy_ssh_private_key: ${{ secrets.TRELLIS_DEPLOY_SSH_PRIVATE_KEY }}
          trellis_deploy_ssh_known_hosts: ${{ secrets.TRELLIS_DEPLOY_SSH_KNOWN_HOSTS }}
          ansible_vault_password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          dry_run: true
